# Generated by Django 3.2.4 on 2021-10-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_messages', '0002_auto_20210629_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category_type',
            field=models.IntegerField(choices=[(1, 'BREAKDOWN_CASH_MACHINE'), (2, 'BREAKDOWN_APP'), (3, 'BREAKDOWN_WEBSITE'), (4, 'FRAUD_BANKING_CARD'), (5, 'FRAUD_TELEPHONE'), (6, 'FRAUD_CASH_MACHINE')], null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='coordinates',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='problem_type',
            field=models.IntegerField(choices=[(1, 'FRAUD'), (2, 'BREAKDOWN')], null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
