# Generated by Django 3.2.4 on 2021-10-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_messages', '0003_auto_20211009_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, 'New Message'), (1, 'Subject Detected'), (2, 'Problem Detected'), (3, 'Category Detected'), (4, 'Tone Detected'), (5, 'Geo Position Detected'), (6, 'Marked Message')], default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='category_type',
            field=models.IntegerField(choices=[(1, 'Cash Machine Breakdown'), (2, 'App Breakdown'), (3, 'Website Breakdown'), (4, 'Banking Card Fraud'), (5, 'Telephone Fraud'), (6, 'Cash Machine Fraud')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='problem_type',
            field=models.IntegerField(choices=[(1, 'Fraud'), (2, 'Breakdown')], null=True),
        ),
    ]
