# Generated by Django 3.2.4 on 2021-12-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_messages', '0004_auto_20211010_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='problem_type',
            field=models.IntegerField(choices=[(0, 'No problem'), (1, 'Fraud'), (2, 'Breakdown')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, 'New Message'), (1, 'Subject Detected'), (2, 'Problem Detected'), (3, 'Category Detected'), (4, 'Tone Detected'), (5, 'Coordinates Detected'), (6, 'Marked Message')], default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social_network_messages.city'),
        ),
    ]
