# Generated by Django 3.2.4 on 2021-12-29 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_messages', '0010_alter_message_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 18, 56, 15, 974962)),
        ),
    ]
