# Generated by Django 3.2.4 on 2022-01-16 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_messages', '0012_auto_20220109_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='emotionality',
            field=models.IntegerField(choices=[(0, 'Not Emotional'), (1, 'Low Emotional'), (2, 'High Emotional'), (3, 'Very High Emotional')], default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='tone',
            field=models.IntegerField(choices=[(0, 'Neutral'), (1, 'Positive'), (2, 'Negative')], default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='category_type',
            field=models.IntegerField(choices=[(0, 'Not Detected'), (1, 'Cash Machine Breakdown'), (2, 'App Breakdown'), (3, 'Telephone Fraud'), (4, 'Cash Machine Fraud')], default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 19, 8, 37, 399869)),
        ),
        migrations.AlterField(
            model_name='message',
            name='problem_type',
            field=models.IntegerField(choices=[(0, 'No Problem'), (1, 'Fraud'), (2, 'Breakdown')], default=0),
        ),
    ]
