# Generated by Django 3.2.4 on 2022-01-17 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_messages', '0013_auto_20220116_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category_type',
            field=models.IntegerField(choices=[(0, 'Not Detected'), (1, 'Cash Machine Breakdown'), (2, 'App Breakdown'), (3, 'Telephone Fraud'), (4, 'Cash Machine Fraud')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 10, 28, 42, 289368)),
        ),
        migrations.AlterField(
            model_name='message',
            name='emotionality',
            field=models.IntegerField(choices=[(0, 'Not Emotional'), (1, 'Low Emotional'), (2, 'High Emotional'), (3, 'Very High Emotional')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default='Unnamed', max_length=400),
        ),
        migrations.AlterField(
            model_name='message',
            name='problem_type',
            field=models.IntegerField(choices=[(0, 'No Problem'), (1, 'Fraud'), (2, 'Breakdown')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='tone',
            field=models.IntegerField(choices=[(0, 'Neutral'), (1, 'Positive'), (2, 'Negative')], null=True),
        ),
    ]
