# Generated by Django 3.2.4 on 2022-01-20 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_messages', '0016_auto_20220119_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 9, 19, 50, 476920)),
        ),
    ]
