# Generated by Django 3.2.4 on 2022-01-26 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_messages', '0017_auto_20220120_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='probability',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 23, 47, 14, 969415)),
        ),
    ]
